<a href="https://colab.research.google.com/github/one-2730/ESAA-24-2/blob/Assignment/ESAA_YB_1108_Session.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. 단순 선형 회귀 분석**
- 전복의 나이를 예측하는 선형회귀모델을 생성하세요.
- 전복의 ‘성별’, ‘키’, ‘지름’, ‘높이’, ‘전체무게’, ‘몸통무게’, ‘내장무게’, ‘껍질무게’를 이용해 ‘껍질의 고리 수’를 예측한 뒤, **예측된 ‘껍질의 고리 수’에 1.5를 더하면 전복의 나이**가 됩니다.

In [1]:
# 기본 모듈 불러오기
import numpy as np
import pandas as pd

**1) 데이터 load 및 변형**

In [4]:
# 데이터 로드
data = pd.read_csv("abalone.csv")
data.head()
print(data.shape)

# 성별 M은 Male, F는 Female, I는 Infant 이므로 따로 열 만들기
for label in "MFI":
    data[label] = data["Sex"] == label
data.drop('Sex', axis=1, inplace=True)

(4177, 9)

**2) X, y 선택**
: y는 Rings열, X는 Rings열을 제외한 나머지를 선택하되 전부 실수가 되도록 한다.

In [19]:
# X,y 데이터 선택
y = data['Rings']

X = data.drop('Rings', axis = 1)
X.astype('float')

X.head()

,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,M,F,I
0,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,True,False,False
1,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,True,False,False
2,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,False,True,False
3,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,True,False,False
4,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,False,False,True

 **3) train/test set 분리**

In [13]:
# 필요한 모듈 불러오기
from sklearn.model_selection import train_test_split

In [14]:
# train과 test set 분리 (train:test = 7:3 비율로)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

**4) 선형회귀모델 생성, 모델 예측치 구하기**

In [15]:
#필요한 모듈 불러오기
from sklearn.linear_model import LinearRegression

In [17]:
#선형회귀모델 생성 및 훈련
LinReg = LinearRegression()
LinReg.fit(X_train, y_train)

In [21]:
# 모델 예측치 구하기
pred = LinReg.predict(X_test)
# 모델 예측치를 활용해 최종적으로 전복의 나이를 예측
age_pred = pred+1.5

**5) 모델 평가: MSE, RMSE, R2 score, corr 구하기**

In [22]:
#필요한 모듈 불러오기
from sklearn.metrics import mean_squared_error, root_mean_squared_error, r2_score

- MSE, RMSE

In [23]:
#mse, rmse

mse = mean_squared_error(y_test, pred)
rmse = root_mean_squared_error(y_test, pred)

print(mse, rmse)

5.027095137975331 2.242118448694299

- R2 score

In [24]:
#R2 score 측정

r2 = r2_score(y_test, pred)
print(r2)

0.5335193072109703

- 회귀 절편값

In [25]:
#회귀 절편 값
print(LinReg.intercept_)

3.526668849283725

- 회귀 계수 값

In [26]:
#회귀 계수 값
print(LinReg.coef_)

[  1.02535708  10.29229991   9.02058197   8.89629563 -19.89008751
 -11.0137543    8.99221761   0.33851862   0.26769718  -0.6062158 ]

- 상관계수

Hint: corr 함수 이용.

In [34]:
# 상관계수 구하기

df = pd.DataFrame({'y_pred' : pred, 'y_test': y_test})
df.corr()

          y_pred    y_test
y_pred  1.000000  0.730677
y_test  0.730677  1.000000

# **2. Polynomial features**

In [28]:
# PolynomialFeatures 라이브러리 호출

from sklearn.preprocessing import PolynomialFeatures

In [27]:
# 임의 데이터 생성

X = np.arange(6).reshape(3, 2)

df =  pd.DataFrame(X)
df.columns = ['x_1','x_2']
df

   x_1  x_2
0    0    1
1    2    3
2    4    5

In [29]:
# 차원은 2로 설정
# fit_transform 메소드를 통해 데이터 변환
# PolynomialFeatures로 변환 된 데이터를 데이터 프레임 형태로 변환

poly = PolynomialFeatures(degree = 2)
poly_ftr = poly.fit_transform(X)
df_poly = pd.DataFrame(poly_ftr)

In [31]:
# df_poly의 컬럼을 1,x1,x2,x1^2,x1*x2,x2^2 로 변경

df_poly.columns = ['1','x1','x2','x1^2','x1*x2','x2^2']

In [32]:
df_poly

     1   x1   x2  x1^2  x1*x2  x2^2
0  1.0  0.0  1.0   0.0    0.0   1.0
1  1.0  2.0  3.0   4.0    6.0   9.0
2  1.0  4.0  5.0  16.0   20.0  25.0